server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: HOTEL-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/**